# -*- coding: utf-8 -*-
"""Myntra_images_title.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11EJDwG5NhVU0x34MHYFwsQ1ml8nNHTez
"""

# from google.colab import drive
# drive.mount('/content/gdrive')

import pandas as pd
from PIL import Image
import os
import re
import string
import numpy as np
import matplotlib.pyplot as plt
import cv2
import random
import plotly.express as px

# import missingno as msno

"""**CSV Files**"""
gdrive_csv = '/content/gdrive/MyDrive/Myntra_Hackathon/data/images_metadata.csv'
# local_csv = 'C:/Users/dell/Desktop/data/images_metadata.csv'
local_csv = 'images_metadata.csv'
metadata = pd.read_csv(local_csv)
# metadata = pd.read_csv(gdrive_csv)
metadata.sample(5)

metadata.sample(5)

"""**Image folders**"""

#Image Folder Paths
common = '/static/images/'
north_jpg_directory = common + 'north/'
northeast_jpg_directory = common + 'north-east/'
east_jpg_directory = common + 'east/'
south_jpg_directory = common + 'south/'
western_jpg_directory = common + 'western/'


def display_multiple_img(images_paths, region):
    """
    Function to Return Images from Dataset as JSON.
    
    parameters: images_path for the selected region
                region is selected region
    """
    dataframe = metadata[metadata['region']==region]
    # print(dataframe)
    for i in dataframe.index:
      dataframe.loc[i,'images'] = images_paths + dataframe.loc[i,'images']
      
    # dataframe = dataframe[['images','title']] 
    dataframe = dataframe[['images','title','price']]  
    return dataframe
        

def clean_region(region):
  region = re.sub('\s+', '', region.lower())
  return region

def search(query_region):
  query_region = clean_region(query_region)
  image_path = query_region
  if query_region == 'north':
    image_path = north_jpg_directory
  elif query_region == 'north-east':
    image_path = northeast_jpg_directory
  elif query_region == 'east':
    image_path = east_jpg_directory 
  elif query_region == 'south':
    image_path = south_jpg_directory
  elif query_region == 'western':
    image_path = western_jpg_directory
  return display_multiple_img(image_path,query_region)

# search('north')

# search('south')